# Generated by Django 3.2.5 on 2022-01-09 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='now_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
