# Generated by Django 3.2.5 on 2022-01-09 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_now_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
